#!/bin/sh 

if [ ! -d data ]; then 
	mkdir data
fi 

if [ ! -d results ]; then 
	mkdir results
fi 

echo Making executables in root directory
echo
make clean
make 
# ------------------- ok

cd prowgen
echo 
echo Making ProWGen
echo
make clean
make
cp ProWGen .. 
# ------------------- ok

cd ../webproxysim 
echo 
echo Making CacheDriver
echo 
make clean
make
cp CacheDriver .. 
# ------------------- ok

cd ../pop
echo
echo Making popularity 
echo 
make clean
make 
cp popularity ..
# ------------------- ok

cd ../locality 
echo 
echo Making lrustack and freqsize
echo
make clean
make
cp lrustack .. 
cp freqsize .. 


cd ..

